blank_issues_enabled: true
contact_links:
  - name: Questions and Discussion
    url: https://github.com/wangzi5151/github-complete-guide/discussions
    about: Use GitHub Discussions for communication and discussion
